sudo: required
language: generic
services:
- docker
before-install:
- docker build -t reactapp -f Dockerfile.dev .
script:
- docker run -e CI=true reactapp npm run test
deploy:
  provider: gae
  keyfile: docker-278914-180552d8aba3.json
  project: docker-278914
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_bb5679275c9e_key -iv $encrypted_bb5679275c9e_iv
  -in docker-278914-180552d8aba3.json.enc -out docker-278914-180552d8aba3.json -d
